### ISSUE TITLE
pipes changed length

### ISSUE THREAD

**Issue by andreyskv** [kendfrey/high-pressure-pipes#4]
Need to use copper-tungsten-pipe (new higher tier) from bobs otherwise  underground pipes are too short after 0.16->0.17 upgrade. tungsten pipe length downgraded.

**Comment by JDOGG88** [comment]
Just created a pull request that will allow it to work with Factorio version 0.18 and add in these new pipes.

**Comment by kendfrey** [comment]
Closed via #5.
